### ISSUE TITLE
mark abandoned the not used anymore dot packages

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dotkernel#24]
packages that was required in version 1.0
and are not required in version 3

**Comment by bidi47** [comment]
these are the packages not used in dotkernel/frontend in V3.0

dot-authentication
dot-authentication-service
dot-authentication-web
dot-user

dot-controller-plugin-authentication
dot-controller-plugin-authorization
dot-controller-plugin-flashmessenger
dot-controller-plugin-forms
dot-controller-plugin-mail
dot-controller-plugin-session

dot-filter
dot-validator
dot-inputfilter
dot-hydrator

dot-mapper

dot-paginator

dot-cache

**Comment by alexmerlin** [comment]
As a conclusion, all of [these](https://github.com/orgs/dotkernel/repositories?q=&type=archived&language=&sort=name) packages have been archived, except for [dot-authentication](https://github.com/dotkernel/dot-authentication) and [dot-cache](https://github.com/dotkernel/dot-cache), which are kept as active for now.
