### ISSUE TITLE
review requirements

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dotkernel#3]
Server-Requirements.md file 
each php extension listed need to be reviewed
- if is default in php 7.1 installation, remove it from the list 
- if is really used in DK3, then keep it 
- if is not used, to be removed

**Comment by gabidj** [comment]
Users must assure the extensions exist. 

PHP7 comes with less extensions pre-installed.

**Comment by gabidj** [comment]
New version 

 * memory_limit >= 128M
 * upload_max_filesize and post_max_size >= 100M (depending on your data)
 * mbstring
 * CLI SAPI (for Cron Jobs)
 * Composer (added to $PATH)

 Recommendations:
 * opcache 
 * pdo_mysql or mysqli (if using MySql or MariaDb as RDBMS)
 * dom - if working with markup files structure (html, xml, etc)
 * simplexml - working with xml files
 * gd, exif - if working with images
 * zlib, zip, bz2 - if compessing files

**Comment by gabidj** [comment]
The new requirements version was added
