### ISSUE TITLE
composer project install failed

### ISSUE THREAD

**Issue by bidi47** [dotkernel/dotkernel#4]
I tried following the install instructions for Installing DotKernel3 frontend. On this page it says that one requirement is PHP >= 5.6 (I had 5.6.10 initially), but composer could only create the project when I installed PHP 7.1.
http://docs.dotkernel.com/Getting-Started/Server-Requirements.html

**Comment by n3vrax** [comment]
Please use the package documentation for now, where available. Go to the package repository and see the README.md file, as they are updated more frequently

For frontend installation steps, you can [click here](https://github.com/dotkernel/frontend/blob/master/README.md)

**Comment by gabidj** [comment]
The install guide was written when 5.6 was still a valid dependency for dot
kernel.

The latest version has PHP 7.1 as the minimum requirement. The install
guide will be updated. Thank you for the notice.

Assign @gabidj

**Comment by bidi47** [comment]
Got it. Thank you.

**Comment by gabidj** [comment]
Updated System Requirements
