### ISSUE TITLE
frontend installed, but fails

### ISSUE THREAD

**Issue by bidi47** [dotkernel/dotkernel#5]
I installed DK3 frontend successfully and managed to see load the page on http://localhost:8080/, but when I click on any other link I get this error in the command prompt.

> php -S 0.0.0.0:8080 -t public public/index.php
[Tue Apr 11 18:08:56 2017] 127.0.0.1:4313 [200]: /css/style.css
[Tue Apr 11 18:08:56 2017] 127.0.0.1:4315 [200]: /js/main.js
[Tue Apr 11 18:08:56 2017] 127.0.0.1:4316 [200]: /favicon.ico
[Tue Apr 11 18:08:56 2017] 127.0.0.1:4317 [200]: /img/logo.svg
[Tue Apr 11 18:08:56 2017] 127.0.0.1:4318 [200]: /img/user.png
[Tue Apr 11 18:08:56 2017] 127.0.0.1:4320 [200]: /img/arrow_center.png
[Tue Apr 11 18:08:56 2017] 127.0.0.1:4321 [200]: /img/open.png
[Tue Apr 11 18:09:04 2017] 127.0.0.1:4337 Invalid request (Unexpected EOF)
[Tue Apr 11 18:09:08 2017] 127.0.0.1:4341 [200]: /img/close.png
[Zend Utils 2017-04-11T18:09:19] Process 6204 has exited unexpectedly. Minidump is at C:\Users\bidi\AppData\Local\Temp\zend_dump\p6204.mdmp.
Script php -S 0.0.0.0:8080 -t public public/index.php handling the serve event returned with error code -529697949

**Comment by n3vrax** [comment]
Please confirm you are using php version >= 7.1. 
I don't know if could be helpful, but could you attach the dump file here?

This seems to be hard to debug, as it is a server crash.
Also, make sure for now that you follow the steps described [here](https://github.com/dotkernel/frontend/blob/master/README.md) for installation, as it is more up to date

**Comment by bidi47** [comment]
Yes, I'm using PHP 7.1. I'll retry the setup from the other page.

**Comment by gabidj** [comment]
Was this issue resolved?

**Comment by bidi47** [comment]
As far as I'm concerned, yes, it's solved.
